### ISSUE TITLE
Won't work on Spigot 1.21.11

### ISSUE THREAD

**Issue by kotaru34** [MagicCheese1/Damage-Indicator#55]
As the title says. Plugin version 2.2.4 (latest atm).

Console output on plugin load:
`[18:21:10] [Server thread/INFO]: [DamageIndicator] Enabling DamageIndicator v2.2.4
[18:21:10] [Server thread/ERROR]: Error occurred while enabling DamageIndicator v2.2.4 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/world/level/Level
	at io.github.magiccheese1.damageindicator.DamageIndicatorImpl.onEnable(DamageIndicatorImpl.java:84)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:492)
	at org.bukkit.craftbukkit.v1_21_R7.CraftServer.enablePlugin(CraftServer.java:577)
	at org.bukkit.craftbukkit.v1_21_R7.CraftServer.enablePlugins(CraftServer.java:491)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:680)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:468)
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:365)
	at net.minecraft.server.MinecraftServer.A(MinecraftServer.java:1064)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:339)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.level.Level
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:160)
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 12 more`

**Comment by MagicCheese1** [comment]
Yes, thank you for creating an issue. I am aware of this and already mentioned it in the changelog. This is probably caused by the remapping build step. I was waiting for a pull request to the remapping plugin to be merged. I'll check later if it fixes the issue or if it's even merged already.
